coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null

codecov:
  token: 08a9c11b-ea34-46f8-a03c-90802a1528e9