// Settings Reducer
export const CHANGE_SETTING_VALUE = "SETTINGS/CHANGE_SETTING_VALUE";

// UI Reducer
export const TOGGLE_SETTINGS_MENU = "UI/TOGGLE_SETTINGS_MENU";
export const TOGGLE_FILTERS_MENU = "UI/TOGGLE_FILTERS_MENU";

// Tracks Reducer
export const SET_SEEK_POSITION = "TRACKS/SET_SEEK_POSITION";
export const SET_VIEW = "TRACKS/SET_VIEW";
export const MAGNIFY_VIEW = "TRACKS/MAGNIFY_VIEW";
export const SHIFT_VIEW = "TRACKS/SHIFT_VIEW";
export const SET_CURRENTLY_PLAYING = "TRACKS/SET_CURRENTLY_PLAYING";
export const ADD_TRACK = "TRACKS/ADD_TRACK";
export const REMOVE_TRACK = "TRACKS/REMOVE_TRACK";
export const GENERATE_NEXT_TRACK_ID = "TRACKS/GENERATE_NEXT_TRACK_ID";
export const SELECT_TRACK = "TRACKS/SELECT_TRACK";
export const SELECTED_TRACK_SHIFT = "TRACKS/SELECTED_TRACK_SHIFT";
export const TOGGLE_TRACK_MUTE = "TRACKS/TOGGLE_TRACK_MUTE";
export const SET_TRACK_SAMPLE_RATE = "TRACKS/SET_TRACK_SAMPLE_RATE";
export const SET_TRACK_FILE_NAME = "TRACKS/SET_TRACK_FILE_NAME";
export const SET_TRACK_LENGTH = "TRACKS/SET_TRACK_LENGTH";
export const SET_TRACK_GRAINS = "TRACKS/SET_TRACK_GRAINS";
export const SET_TRACK_MAX_AMPLITUDE = "TRACKS/SET_TRACK_MAX_AMPLITUDE";
