export const CHANGE_SETTING_VALUE = "SETTINGS/CHANGE_SETTING_VALUE";
export const SET_SEEK_POSITION = "TRACKS/SET_SEEK_POSITION";
export const SET_VIEW = "TRACKS/SET_VIEW";
export const MAGNIFY_VIEW = "TRACKS/MAGNIFY_VIEW";
export const SHIFT_VIEW = "TRACKS/SHIFT_VIEW";
export const TOGGLE_SETTINGS_MENU = "UI/TOGGLE_SETTINGS_MENU";
export const TOGGLE_FILTERS_MENU = "UI/TOGGLE_FILTERS_MENU";
